In [45]:
import torch
import numpy as np

In [46]:
def describe(t):
    print()
    print(t,t.shape,t.dtype)
    print()

## Functions where a tensor is created from 0 tensors

In [47]:
#from list
l = [[1,2,3],[4,5,6]]
a = torch.tensor(l)
print("Tensor from list",l, "=======>" , a, "with shape",a.shape,"with dtype",a.dtype,"with requires_grad",a.requires_grad,"by default")

#from numpy array
n = np.random.rand(2,3)
b = torch.tensor(n)
print("Tensor from numpy array",n, "=======>" , b, "with shape",b.shape,"with dtype",b.dtype,"with requires_grad",b.requires_grad,"by default")

c = torch.from_numpy(n)
print("Tensor from numpy array",n, "=======>" , c, "with shape",c.shape,"with dtype",c.dtype,"with requires_grad",c.requires_grad,"by default")




Tensor from list [[1, 2, 3], [4, 5, 6]] =======> tensor([[1, 2, 3],
        [4, 5, 6]]) with shape torch.Size([2, 3]) with dtype torch.int64 with requires_grad False by default
Tensor from numpy array [[0.83410477 0.95239414 0.91786261]
 [0.23167481 0.91089324 0.4643033 ]] =======> tensor([[0.8341, 0.9524, 0.9179],
        [0.2317, 0.9109, 0.4643]], dtype=torch.float64) with shape torch.Size([2, 3]) with dtype torch.float64 with requires_grad False by default
Tensor from numpy array [[0.83410477 0.95239414 0.91786261]
 [0.23167481 0.91089324 0.4643033 ]] =======> tensor([[0.8341, 0.9524, 0.9179],
        [0.2317, 0.9109, 0.4643]], dtype=torch.float64) with shape torch.Size([2, 3]) with dtype torch.float64 with requires_grad False by default


In [48]:
#takes in dims
describe(torch.zeros(2,3))
#takes in dims
describe(torch.ones(2,3))



tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3]) torch.float32


tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3]) torch.float32



In [49]:
#takes in dims
describe(torch.rand(2,3))
#takes in dims
describe(torch.randn(2,3))


tensor([[0.4064, 0.7071, 0.6499],
        [0.8302, 0.2003, 0.5052]]) torch.Size([2, 3]) torch.float32


tensor([[ 2.0041, -0.0551,  1.4880],
        [-0.5075,  1.0443, -0.8530]]) torch.Size([2, 3]) torch.float32



In [50]:
#min max interval and max is excluded
describe(torch.arange(1,5))
describe(torch.arange(1.0,10.0,2))

#min max number_of_values and max is included
describe(torch.linspace(1,5,10))


tensor([1, 2, 3, 4]) torch.Size([4]) torch.int64


tensor([1., 3., 5., 7., 9.]) torch.Size([5]) torch.float32


tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000]) torch.Size([10]) torch.float32



## Functions where a tensor is altered(reshape,squeeze,unsqueeze)

In [52]:
#reshaping starts from the innermost dimension
#traverse on a flat tensor and start accumulating the innermost dimension
#0,1,2,3(for the dimension 4 in (2,4))
d = torch.arange(8)
describe(d)
describe(d.reshape(2,4))

e = torch.rand((4,3,2))
print(e)
#they both yeild the same output
describe(e.reshape(4,6))
describe(e.reshape(-1).reshape(4,6))


tensor([0, 1, 2, 3, 4, 5, 6, 7]) torch.Size([8]) torch.int64


tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]]) torch.Size([2, 4]) torch.int64

tensor([[[0.6431, 0.7386],
         [0.2529, 0.5463],
         [0.8872, 0.2032]],

        [[0.5340, 0.5104],
         [0.9807, 0.1679],
         [0.0379, 0.5528]],

        [[0.2201, 0.2503],
         [0.5550, 0.8240],
         [0.3631, 0.3262]],

        [[0.3391, 0.5989],
         [0.3123, 0.4197],
         [0.9391, 0.2328]]])

tensor([[0.6431, 0.7386, 0.2529, 0.5463, 0.8872, 0.2032],
        [0.5340, 0.5104, 0.9807, 0.1679, 0.0379, 0.5528],
        [0.2201, 0.2503, 0.5550, 0.8240, 0.3631, 0.3262],
        [0.3391, 0.5989, 0.3123, 0.4197, 0.9391, 0.2328]]) torch.Size([4, 6]) torch.float32


tensor([[0.6431, 0.7386, 0.2529, 0.5463, 0.8872, 0.2032],
        [0.5340, 0.5104, 0.9807, 0.1679, 0.0379, 0.5528],
        [0.2201, 0.2503, 0.5550, 0.8240, 0.3631, 0.3262],
        [0.3391, 0.5989, 0.3123, 0.4197, 0.9391, 0.2328]]) torch.Size([4, 6]) torch.

In [58]:
#gets rid of the dim if it is 1
f = torch.rand(1,3,2)
describe(f)
describe(torch.squeeze(f,dim=0))

g = torch.rand(3,1,2)
describe(g)
describe(torch.squeeze(g,dim=1))


tensor([[[0.6097, 0.2096],
         [0.3063, 0.7557],
         [0.9053, 0.1049]]]) torch.Size([1, 3, 2]) torch.float32


tensor([[0.6097, 0.2096],
        [0.3063, 0.7557],
        [0.9053, 0.1049]]) torch.Size([3, 2]) torch.float32


tensor([[[0.0119, 0.7893]],

        [[0.3025, 0.0688]],

        [[0.9503, 0.6213]]]) torch.Size([3, 1, 2]) torch.float32


tensor([[0.0119, 0.7893],
        [0.3025, 0.0688],
        [0.9503, 0.6213]]) torch.Size([3, 2]) torch.float32



In [59]:
#adds a dimension on dim
h = torch.rand(3,2)
describe(h)
describe(torch.unsqueeze(h,dim=0))


tensor([[0.4634, 0.7433],
        [0.5654, 0.0455],
        [0.7890, 0.0802]]) torch.Size([3, 2]) torch.float32


tensor([[[0.4634, 0.7433],
         [0.5654, 0.0455],
         [0.7890, 0.0802]]]) torch.Size([1, 3, 2]) torch.float32



## Functions where two tensors are operated upon

In [66]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
describe(a)
describe(b)

#a new dimension is always created while using stack
print("dim=0 stacking")
#this is similar to creating a batch comprising of a and b
describe(torch.stack([a,b]))
print("dim=1 stacking")
#this is similar to joining respective rows to create a new dimension
describe(torch.stack([a,b],dim=1))
print("dim=2 stacking")
#this is similar to element to element joining
describe(torch.stack([a,b],dim=2))


tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3]) torch.int64


tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3]) torch.int64

dim=0 stacking

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) torch.Size([2, 2, 3]) torch.int64

dim=1 stacking

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]]) torch.Size([2, 2, 3]) torch.int64

dim=2 stacking

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]]) torch.Size([2, 3, 2]) torch.int64



In [68]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
describe(a)
describe(b)

#cat joins tensors along existing dimensions
print("dim=0 stacking")
#simply concatinating row wise i.e. 4 rows and 3 columns in output
describe(torch.cat([a,b],dim=0))
print("dim=1 stacking")
#simply concatinating column wise i.e. 2 rows and 6 columns in output
describe(torch.cat([a,b],dim=1))


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) torch.Size([2, 2, 3]) torch.int64


tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]) torch.Size([2, 2, 3]) torch.int64



In [82]:
#2,3,4
#visualize this as two sheets(depth) each sheet containing 3 rows and 4 columns. These sheets stand parallel to each other
a = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
describe(a)


#3,2,4
#here we need to convert 3 sheets to 2 and each sheet would contain two rows and four columns
#View the visualization of "a" from the top. We can visualize three sheets stacked on top of one another(new depth) with rows of respective sheets now combined as 
#rows of the respective new sheets.
b = torch.transpose(a,0,1)
describe(b)

c = torch.transpose(a,1,2)
describe(c)

#here we need to convert 2 sheets into 4 sheets and each sheet would contain 3 rows and 2 columns
#View the visualization of "a" from the side. We can visualize 4 sheets stacked one behind another with elements/columns of respective sheets now combined as 
#columns of the respective new sheets.
d = torch.transpose(a,0,2)
describe(d)


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]) torch.Size([2, 3, 4]) torch.int64


tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]]) torch.Size([3, 2, 4]) torch.int64


tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]]) torch.Size([2, 4, 3]) torch.int64


tensor([[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]]) torch.Size([4, 3, 2]) torch.int64



In [85]:
a = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
describe(a)

#sum along the outermost dim(along batch)
#keepdim=False squeezes the dim that converts to 1 on sum
describe(torch.sum(a,dim=0,keepdim=False))
describe(torch.sum(a,dim=0,keepdim=True))

#sum along the rows
describe(torch.sum(a,dim=1,keepdim=False))
describe(torch.sum(a,dim=1,keepdim=True))

#sum along the columns
describe(torch.sum(a,dim=2,keepdim=False))
describe(torch.sum(a,dim=2,keepdim=True))


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]) torch.Size([2, 3, 4]) torch.int64


tensor([[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]]) torch.Size([3, 4]) torch.int64


tensor([[[14, 16, 18, 20],
         [22, 24, 26, 28],
         [30, 32, 34, 36]]]) torch.Size([1, 3, 4]) torch.int64


tensor([[15, 18, 21, 24],
        [51, 54, 57, 60]]) torch.Size([2, 4]) torch.int64


tensor([[[15, 18, 21, 24]],

        [[51, 54, 57, 60]]]) torch.Size([2, 1, 4]) torch.int64


tensor([[10, 26, 42],
        [58, 74, 90]]) torch.Size([2, 3]) torch.int64


tensor([[[10],
         [26],
         [42]],

        [[58],
         [74],
         [90]]]) torch.Size([2, 3, 1]) torch.int64



In [95]:
attn = torch.rand(1,4,8,8)
print(attn)
attn = attn.masked_fill(torch.tril(torch.ones(8,8)).view(1,1,8,8)[:,:,:8,:8] == 0,float('-inf'))
print(attn)
torch.nn.functional.softmax(attn,dim=-1)

tensor([[[[3.3697e-01, 2.0672e-01, 7.0715e-01, 9.5798e-02, 4.7415e-01,
           8.4588e-01, 3.6443e-01, 7.0721e-01],
          [7.9038e-01, 2.6720e-01, 6.0252e-01, 8.0661e-01, 9.7861e-01,
           9.3530e-01, 9.8666e-01, 3.4964e-01],
          [6.9719e-01, 4.2518e-01, 1.7698e-01, 8.9443e-01, 6.6520e-01,
           8.1274e-01, 3.8257e-01, 1.0800e-01],
          [4.5931e-02, 1.2105e-01, 5.6327e-01, 2.9143e-01, 1.8205e-01,
           6.4921e-01, 7.9034e-01, 1.9662e-02],
          [7.8112e-01, 6.9247e-01, 9.8113e-01, 5.7140e-01, 1.3768e-01,
           4.1122e-01, 2.3906e-01, 9.9297e-01],
          [6.4141e-02, 8.8003e-02, 6.7621e-04, 6.9288e-01, 1.7235e-01,
           1.2055e-01, 7.1414e-01, 9.3480e-01],
          [3.9432e-01, 2.2759e-01, 3.8004e-01, 5.5961e-01, 5.4823e-01,
           1.5178e-01, 8.0643e-01, 7.3773e-01],
          [1.9700e-01, 4.9599e-01, 7.4360e-01, 7.9493e-01, 5.7901e-01,
           4.2748e-01, 6.9591e-01, 1.5630e-02]],

         [[5.3708e-01, 7.0153e-01, 4.5942e-01,

tensor([[[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.6279, 0.3721, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.4244, 0.3233, 0.2523, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.1987, 0.2142, 0.3333, 0.2539, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.2236, 0.2046, 0.2731, 0.1813, 0.1175, 0.0000, 0.0000, 0.0000],
          [0.1426, 0.1461, 0.1339, 0.2675, 0.1590, 0.1509, 0.0000, 0.0000],
          [0.1338, 0.1133, 0.1319, 0.1579, 0.1561, 0.1050, 0.2021, 0.0000],
          [0.0901, 0.1215, 0.1556, 0.1638, 0.1320, 0.1134, 0.1484, 0.0751]],

         [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.3084, 0.6916, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.3322, 0.2284, 0.4394, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.2493, 0.2378, 0.3124, 0.2005, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.1692, 0.2436, 0.2410, 0.1089, 0.2373, 0.0000, 0.0000, 0.0000],
          